In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\lalit\OneDrive\Documents\Hospital Data.csv")

In [65]:
df

,PatientID,FirstName,LastName,Gender,Age,Phone,Email,Department,AdmissionType,Diagnosis,AdmissionDate,DischargeDate,PaymentMethod,DischargeStatus,BillAmount,Name,Year
0,1,Vijay,Kumar,Female,48,-9746317122,vijay.gupta40@example.com,Cardiology,Elective,COVID-19,2022-02-18,23-04-2022,Credit Card,Referred,126986,Vijay Kumar,2022
1,2,Sita,Kumar,Male,72,-7478163236,sita.kumar98@example.com,General Surgery,Emergency,Cancer,2023-01-26,20-07-2022,Credit Card,Recovered,160450,Sita Kumar,2023
2,3,Kiran,Yadav,Male,60,-7107420278,ravi.kumar9@example.com,Psychiatry,Maternity,Asthma,2022-11-15,14-11-2023,Cash,Expired,162830,Kiran Yadav,2022
3,4,Anil,Kumar,Male,81,-8181241852,sita.verma16@example.com,Dermatology,Elective,Fracture,2023-01-08,05-11-2023,Cash,Recovered,72388,Anil Kumar,2023
4,5,Vijay,Gupta,Male,6,-8051802421,sunita.nair5@example.com,Nephrology,Routine,Cancer,2022-04-28,26-10-2023,Credit Card,Recovered,13669,Vijay Gupta,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,Sunita,Gupta,Female,86,-8986825432,manoj.sharma90@example.com,Psychiatry,Maternity,Cancer,2022-06-18,03-03-2023,Credit Card,Expired,80216,Sunita Gupta,2022
49996,49997,Amit,Patel,Male,47,-7777552893,manoj.sharma5@example.com,Orthopedics,Emergency,COVID-19,2022-04-02,17-10-2022,Online,Expired,85044,Amit Patel,2022
49997,49998,Manoj,Sharma,Male,11,-7994711040,neha.patel2@example.com,Pediatrics,Elective,Migraine,2023-01-01,15-06-2023,Credit Card,Recovered,45385,Manoj Sharma,2023
49998,49999,Ravi,Patel,Male,39,-8761710207,sita.sharma52@example.com,General Surgery,Maternity,Asthma,2022-10-11,22-11-2023,Insurance,Referred,64218,Ravi Patel,2022
49999,50000,Ravi,Sharma,Female,46,-8061917867,sunita.mehta24@example.com,Cardiology,Routine,COVID-19,2022-06-28,10-10-2022,Cash,Referred,175565,Ravi Sharma,2022

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PatientID        50000 non-null  int64
 1   FirstName        50000 non-null  object
 2   LastName         50000 non-null  object
 3   Gender           50000 non-null  object
 4   Age              50000 non-null  int64
 5   Phone            50000 non-null  int64
 6   Email            50000 non-null  object
 7   Department       50000 non-null  object
 8   AdmissionType    50000 non-null  object
 9   Diagnosis        50000 non-null  object
 10  AdmissionDate    50000 non-null  object
 11  DischargeDate    50000 non-null  object
 12  PaymentMethod    50000 non-null  object
 13  DischargeStatus  50000 non-null  object
 14  BillAmount       50000 non-null  int64
 15  Unnamed: 15      0 non-null      float64
 16  Unnamed: 16      11 non-null     object
dtypes: float64(1), int64(4), object(12)
memory usage: 6.5+ MB

In [5]:
print("Number of Rows",df.shape[0])
print("Number of Columns",df.shape[1])

Number of Rows 50000
Number of Columns 15

In [6]:
df.columns

Index(['PatientID', 'FirstName', 'LastName', 'Gender', 'Age', 'Phone', 'Email',
       'Department', 'AdmissionType', 'Diagnosis', 'AdmissionDate',
       'DischargeDate', 'PaymentMethod', 'DischargeStatus', 'BillAmount'],
      dtype='object')

In [9]:
df.isnull().sum()

PatientID              0
FirstName              0
LastName               0
Gender                 0
Age                    0
Phone                  0
Email                  0
Department             0
AdmissionType          0
Diagnosis              0
AdmissionDate          0
DischargeDate          0
PaymentMethod          0
DischargeStatus        0
BillAmount             0
Unnamed: 15        50000
Unnamed: 16        49989
dtype: int64

In [10]:
Revenue_AdmissionType = df.groupby('AdmissionType')['BillAmount'].sum()

In [11]:
Revenue_AdmissionType

AdmissionType
Elective     1273878754
Emergency    1276185783
Maternity    1248605847
Routine      1255371554
Name: BillAmount, dtype: int64

In [16]:
Total_Revenue=df['BillAmount'].sum()

In [17]:
Total_Revenue

np.int64(5054041938)

In [19]:
Total_Department = df.groupby('Department')['BillAmount'].sum()

In [20]:
Total_Department

Department
Cardiology         453294013
Dermatology        458740550
ENT                455797041
General Surgery    464543414
Nephrology         455698631
Neurology          470512786
Oncology           466918429
Orthopedics        451234094
Pediatrics         461367811
Psychiatry         451034714
Urology            464900455
Name: BillAmount, dtype: int64

In [21]:
Total_Diagnosis = df.groupby('Diagnosis')['BillAmount'].sum()

In [22]:
Total_Diagnosis

Diagnosis
Asthma          510656637
COVID-19        505375284
Cancer          509914690
Depression      493657405
Diabetes        501036415
Fracture        508323831
Hypertension    503349925
Kidney Stone    504599618
Migraine        519426114
Pneumonia       497702019
Name: BillAmount, dtype: int64

In [31]:

print('Total_Patient',df.shape[0])

Total_Patient 50000

In [33]:
df['Gender'].value_counts()

Gender
Male      25053
Female    24947
Name: count, dtype: int64

In [34]:
df['AdmissionType'].value_counts()

AdmissionType
Elective     12555
Emergency    12542
Routine      12463
Maternity    12440
Name: count, dtype: int64

In [35]:
df['Department'].value_counts()

Department
Urology            4657
Neurology          4591
Oncology           4590
General Surgery    4578
Dermatology        4546
Pediatrics         4541
ENT                4519
Cardiology         4517
Nephrology         4512
Orthopedics        4489
Psychiatry         4460
Name: count, dtype: int64

In [36]:
df['Diagnosis'].value_counts()

Diagnosis
Cancer          5087
Fracture        5071
Asthma          5032
COVID-19        5025
Kidney Stone    5024
Migraine        5011
Hypertension    5007
Diabetes        4935
Pneumonia       4922
Depression      4886
Name: count, dtype: int64

In [41]:
Max_Bill = df['BillAmount'].max()

In [38]:
Min_Bill =df['BillAmount'].min()

In [42]:
Max_Age = df['Age'].max()

In [43]:
Max_Age

89

In [44]:
Min_Age = df['Age'].min()

In [45]:
Min_Age

1

In [47]:
df["Name"]=df['FirstName']+" "+df['LastName']

In [48]:
df

,PatientID,FirstName,LastName,Gender,Age,Phone,Email,Department,AdmissionType,Diagnosis,AdmissionDate,DischargeDate,PaymentMethod,DischargeStatus,BillAmount,Name
0,1,Vijay,Kumar,Female,48,-9746317122,vijay.gupta40@example.com,Cardiology,Elective,COVID-19,18-02-2022,23-04-2022,Credit Card,Referred,126986,Vijay Kumar
1,2,Sita,Kumar,Male,72,-7478163236,sita.kumar98@example.com,General Surgery,Emergency,Cancer,26-01-2023,20-07-2022,Credit Card,Recovered,160450,Sita Kumar
2,3,Kiran,Yadav,Male,60,-7107420278,ravi.kumar9@example.com,Psychiatry,Maternity,Asthma,15-11-2022,14-11-2023,Cash,Expired,162830,Kiran Yadav
3,4,Anil,Kumar,Male,81,-8181241852,sita.verma16@example.com,Dermatology,Elective,Fracture,08-01-2023,05-11-2023,Cash,Recovered,72388,Anil Kumar
4,5,Vijay,Gupta,Male,6,-8051802421,sunita.nair5@example.com,Nephrology,Routine,Cancer,28-04-2022,26-10-2023,Credit Card,Recovered,13669,Vijay Gupta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,Sunita,Gupta,Female,86,-8986825432,manoj.sharma90@example.com,Psychiatry,Maternity,Cancer,18-06-2022,03-03-2023,Credit Card,Expired,80216,Sunita Gupta
49996,49997,Amit,Patel,Male,47,-7777552893,manoj.sharma5@example.com,Orthopedics,Emergency,COVID-19,02-04-2022,17-10-2022,Online,Expired,85044,Amit Patel
49997,49998,Manoj,Sharma,Male,11,-7994711040,neha.patel2@example.com,Pediatrics,Elective,Migraine,01-01-2023,15-06-2023,Credit Card,Recovered,45385,Manoj Sharma
49998,49999,Ravi,Patel,Male,39,-8761710207,sita.sharma52@example.com,General Surgery,Maternity,Asthma,11-10-2022,22-11-2023,Insurance,Referred,64218,Ravi Patel
49999,50000,Ravi,Sharma,Female,46,-8061917867,sunita.mehta24@example.com,Cardiology,Routine,COVID-19,28-06-2022,10-10-2022,Cash,Referred,175565,Ravi Sharma

In [49]:
Discharge_Counts=df['DischargeStatus'].value_counts()

In [51]:
Discharge_Counts

DischargeStatus
Expired      16898
Recovered    16635
Referred     16467
Name: count, dtype: int64

In [53]:
Max_Diagnosis= df['Diagnosis'].max()

In [54]:
Max_Diagnosis

'Pneumonia'

In [63]:
df["AdmissionDate"]=pd.to_datetime(df["AdmissionDate"])

C:\Users\lalit\AppData\Local\Temp\ipykernel_12324\2859755148.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["AdmissionDate"]=pd.to_datetime(df["AdmissionDate"])

In [64]:
df["Year"]=df["AdmissionDate"].dt.year

In [66]:
TotalPatients_Year = df["Year"].value_counts()

In [68]:
TotalPatients_Year

Year
2022    25129
2023    24871
Name: count, dtype: int64

In [74]:
df["Month_No"]=df["AdmissionDate"].dt.month

In [76]:
df["Month Name"]=df["AdmissionDate"].dt.month_name()

In [89]:
Monthly_Revenue=df.groupby("Month_No")['BillAmount'].sum().reset_index()

In [85]:
Monthly_Revenue

Month_No
1     428724708
2     389367349
3     413019438
4     428837294
5     433820424
6     421394416
7     425426684
8     427434704
9     423502825
10    425908568
11    411142540
12    425462988
Name: BillAmount, dtype: int64

In [95]:
Month = df.groupby("Month Name")["BillAmount"].sum().reset_index()

In [93]:
Month

   Month Name  BillAmount
0       April   428837294
1      August   427434704
2    December   425462988
3    February   389367349
4     January   428724708
5        July   425426684
6        June   421394416
7       March   413019438
8         May   433820424
9    November   411142540
10    October   425908568
11  September   423502825

In [103]:
Month_Revenue = df.groupby(["Month_No","Month Name"])["BillAmount"].sum().reset_index().round(2)

In [104]:
Month_Revenue

    Month_No Month Name  BillAmount
0          1    January   428724708
1          2   February   389367349
2          3      March   413019438
3          4      April   428837294
4          5        May   433820424
5          6       June   421394416
6          7       July   425426684
7          8     August   427434704
8          9  September   423502825
9         10    October   425908568
10        11   November   411142540
11        12   December   425462988

In [106]:
Month_Revenue1= df.groupby(["Month_No","Month Name"])["BillAmount"].sum().reset_index().round(2)
Month_Revenue1.drop(columns="Month_No")

   Month Name  BillAmount
0     January   428724708
1    February   389367349
2       March   413019438
3       April   428837294
4         May   433820424
5        June   421394416
6        July   425426684
7      August   427434704
8   September   423502825
9     October   425908568
10   November   411142540
11   December   425462988

In [114]:
Average_Age=df["Age"].mean()

In [115]:
Average_Age

np.float64(44.98836)

In [117]:
print("Oldest",df["Age"].max())
print("Youngest",df["Age"].min())

Oldest 89
Youngest 1

In [118]:
Average_Bill = df['BillAmount'].mean()

In [119]:
Average_Bill

np.float64(101080.83876)

In [120]:
Average_Payment=df.groupby("PaymentMethod")["BillAmount"].mean()

In [121]:
Average_Payment

PaymentMethod
Cash           101662.125199
Credit Card    101462.601509
Insurance      100605.227420
Online         100593.110698
Name: BillAmount, dtype: float64

In [122]:
Total_Payment = df.groupby('PaymentMethod')['BillAmount'].sum()

In [123]:
Total_Payment

PaymentMethod
Cash           1274843050
Credit Card    1263919627
Insurance      1243078190
Online         1272201071
Name: BillAmount, dtype: int64

In [144]:
Monthly_Admission=df["Month_No"].value_counts().reset_index().sort_values(by="Month_No", ascending=True)

In [145]:
Monthly_Admission

    Month_No  count
1          1   4285
11         2   3886
9          3   4125
7          4   4172
0          5   4328
8          6   4138
4          7   4198
2          8   4230
6          9   4176
3         10   4225
10        11   4039
5         12   4198

In [130]:
df["DischargeDate"]=pd.to_datetime(df["DischargeDate"])

C:\Users\lalit\AppData\Local\Temp\ipykernel_12324\587596137.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["DischargeDate"]=pd.to_datetime(df["DischargeDate"])

In [133]:
Stay_Days=(df["DischargeDate"]-df["AdmissionDate"]).dt.days

In [135]:
Stay_Days.mean()

np.float64(17.3154)

In [136]:
Average_Gender=df.groupby("Gender")["BillAmount"].mean()

In [137]:
Average_Gender

Gender
Female    101145.955907
Male      101015.997126
Name: BillAmount, dtype: float64

In [138]:
Total_Gender=df.groupby("Gender")["BillAmount"].sum()

In [139]:
Total_Gender

Gender
Female    2523288162
Male      2530753776
Name: BillAmount, dtype: int64

In [148]:
Top10_Diagnosis = df.groupby("Diagnosis")["BillAmount"].sum().head(5).sort_values(ascending=False)

In [149]:
Top10_Diagnosis

Diagnosis
Asthma        510656637
Cancer        509914690
COVID-19      505375284
Diabetes      501036415
Depression    493657405
Name: BillAmount, dtype: int64

In [150]:
Top5_Patient = df.groupby("Name")["BillAmount"].sum().head(5).sort_values(ascending=False)

In [151]:
Top5_Patient

Name
Amit Patel    51938264
Amit Kumar    50453200
Amit Nair     50012207
Amit Gupta    49448905
Amit Mehta    48144280
Name: BillAmount, dtype: int64